-- MySQL Script generated by MySQL Workbench
-- Mon Aug  9 12:45:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_practica_mtto
-- -----------------------------------------------------
-- base de datos de practica mantenimento

-- -----------------------------------------------------
-- Schema db_practica_mtto
--
-- base de datos de practica mantenimento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_practica_mtto` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_practica_mtto` ;

-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_mantenimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_mantenimento` (
  `mantenimento_id` INT NOT NULL AUTO_INCREMENT,
  `mantenimiento_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`mantenimento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_placa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_placa` (
  `placa_id` INT NOT NULL AUTO_INCREMENT,
  `placa_codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`placa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_operador` (
  `operador_id` INT NOT NULL AUTO_INCREMENT,
  `operador_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`operador_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_formato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_formato` (
  `formato_id` INT NOT NULL AUTO_INCREMENT,
  `formato_kilometraje` DOUBLE NOT NULL,
  `formato_fecha_recepcion` DATETIME NOT NULL,
  `tbl_mantenimento_mantenimento_id` INT NOT NULL,
  `tbl_placa_placa_id` INT NOT NULL,
  `tbl_operador_operador_id` INT NOT NULL,
  PRIMARY KEY (`formato_id`),
  CONSTRAINT `fk_tbl_formato_tbl_mantenimento`
    FOREIGN KEY (`tbl_mantenimento_mantenimento_id`)
    REFERENCES `db_practica_mtto`.`tbl_mantenimento` (`mantenimento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_formato_tbl_placa1`
    FOREIGN KEY (`tbl_placa_placa_id`)
    REFERENCES `db_practica_mtto`.`tbl_placa` (`placa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_formato_tbl_operador1`
    FOREIGN KEY (`tbl_operador_operador_id`)
    REFERENCES `db_practica_mtto`.`tbl_operador` (`operador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_tipo_falla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_tipo_falla` (
  `tf_id` INT NOT NULL AUTO_INCREMENT,
  `tf_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_tipo_falla_componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_tipo_falla_componente` (
  `tfc_id` INT NOT NULL AUTO_INCREMENT,
  `tfc_nombre` VARCHAR(45) NOT NULL,
  `tbl_tipo_falla_tf_id` INT NOT NULL,
  PRIMARY KEY (`tfc_id`),
  CONSTRAINT `fk_tbl_tipo_falla_componente_tbl_tipo_falla1`
    FOREIGN KEY (`tbl_tipo_falla_tf_id`)
    REFERENCES `db_practica_mtto`.`tbl_tipo_falla` (`tf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_falla_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_falla_detalle` (
  `fd_id` INT NOT NULL AUTO_INCREMENT,
  `fd_descripcion` MEDIUMTEXT NOT NULL,
  `tbl_tipo_falla_componente_tfc_id` INT NOT NULL,
  `tbl_formato_formato_id` INT NOT NULL,
  PRIMARY KEY (`fd_id`),
  CONSTRAINT `fk_tbl_falla_detalle_tbl_tipo_falla_componente1`
    FOREIGN KEY (`tbl_tipo_falla_componente_tfc_id`)
    REFERENCES `db_practica_mtto`.`tbl_tipo_falla_componente` (`tfc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_falla_detalle_tbl_formato1`
    FOREIGN KEY (`tbl_formato_formato_id`)
    REFERENCES `db_practica_mtto`.`tbl_formato` (`formato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_practica_mtto`.`tbl_orden_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_practica_mtto`.`tbl_orden_trabajo` (
  `ot_id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  `ot` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `rf` VARCHAR(255) NULL,
  `kilometraje` VARCHAR(255) NULL,
  `ciudad` VARCHAR(255) NULL,
  `tipo_ot` VARCHAR(255) NULL,
  `tipo_mtto` VARCHAR(255) NULL,
  `fechareg` VARCHAR(255) NULL,
  `actividad` VARCHAR(255) NULL,
  `detalle` VARCHAR(255) NULL,
  `codigo_sap` VARCHAR(255) NULL,
  `generado` VARCHAR(255) NULL,
  `tipo_tecnico` VARCHAR(255) NULL,
  `personal` VARCHAR(255) NULL,
  `hora_ini` VARCHAR(255) NULL,
  `hora_fin` VARCHAR(255) NULL,
  `observacion` VARCHAR(255) NULL,
  PRIMARY KEY (`ot_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
