# Generated by Django 3.2.6 on 2021-08-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210826_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa_id',
            field=models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.RESTRICT, to='api.mesa', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
